//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DinningManagementModel", "FK_tbl_MealInfo_tbl_userInfo", "tbl_userInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DinningManagementProject.tbl_userInfo), "tbl_MealInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DinningManagementProject.tbl_MealInfo), true)]
[assembly: EdmRelationshipAttribute("DinningManagementModel", "FK_tbl_Uaccount_tbl_userInfo", "tbl_userInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DinningManagementProject.tbl_userInfo), "tbl_Uaccount", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DinningManagementProject.tbl_Uaccount), true)]

#endregion

namespace DinningManagementProject
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DinningManagementEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DinningManagementEntities2 object using the connection string found in the 'DinningManagementEntities2' section of the application configuration file.
        /// </summary>
        public DinningManagementEntities2() : base("name=DinningManagementEntities2", "DinningManagementEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DinningManagementEntities2 object.
        /// </summary>
        public DinningManagementEntities2(string connectionString) : base(connectionString, "DinningManagementEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DinningManagementEntities2 object.
        /// </summary>
        public DinningManagementEntities2(EntityConnection connection) : base(connection, "DinningManagementEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_dalyCost> tbl_dalyCost
        {
            get
            {
                if ((_tbl_dalyCost == null))
                {
                    _tbl_dalyCost = base.CreateObjectSet<tbl_dalyCost>("tbl_dalyCost");
                }
                return _tbl_dalyCost;
            }
        }
        private ObjectSet<tbl_dalyCost> _tbl_dalyCost;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_MealInfo> tbl_MealInfo
        {
            get
            {
                if ((_tbl_MealInfo == null))
                {
                    _tbl_MealInfo = base.CreateObjectSet<tbl_MealInfo>("tbl_MealInfo");
                }
                return _tbl_MealInfo;
            }
        }
        private ObjectSet<tbl_MealInfo> _tbl_MealInfo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Uaccount> tbl_Uaccount
        {
            get
            {
                if ((_tbl_Uaccount == null))
                {
                    _tbl_Uaccount = base.CreateObjectSet<tbl_Uaccount>("tbl_Uaccount");
                }
                return _tbl_Uaccount;
            }
        }
        private ObjectSet<tbl_Uaccount> _tbl_Uaccount;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_userInfo> tbl_userInfo
        {
            get
            {
                if ((_tbl_userInfo == null))
                {
                    _tbl_userInfo = base.CreateObjectSet<tbl_userInfo>("tbl_userInfo");
                }
                return _tbl_userInfo;
            }
        }
        private ObjectSet<tbl_userInfo> _tbl_userInfo;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_dalyCost EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_dalyCost(tbl_dalyCost tbl_dalyCost)
        {
            base.AddObject("tbl_dalyCost", tbl_dalyCost);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_MealInfo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_MealInfo(tbl_MealInfo tbl_MealInfo)
        {
            base.AddObject("tbl_MealInfo", tbl_MealInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Uaccount EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Uaccount(tbl_Uaccount tbl_Uaccount)
        {
            base.AddObject("tbl_Uaccount", tbl_Uaccount);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_userInfo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_userInfo(tbl_userInfo tbl_userInfo)
        {
            base.AddObject("tbl_userInfo", tbl_userInfo);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="ddate">No Metadata Documentation available.</param>
        public ObjectResult<SP_stopNum_Result2> SP_stopNum(Nullable<global::System.DateTime> ddate)
        {
            ObjectParameter ddateParameter;
            if (ddate.HasValue)
            {
                ddateParameter = new ObjectParameter("ddate", ddate);
            }
            else
            {
                ddateParameter = new ObjectParameter("ddate", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction<SP_stopNum_Result2>("SP_stopNum", ddateParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DinningManagementModel", Name="tbl_dalyCost")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_dalyCost : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_dalyCost object.
        /// </summary>
        /// <param name="c_date">Initial value of the C_date property.</param>
        /// <param name="cost">Initial value of the cost property.</param>
        public static tbl_dalyCost Createtbl_dalyCost(global::System.String c_date, global::System.Int32 cost)
        {
            tbl_dalyCost tbl_dalyCost = new tbl_dalyCost();
            tbl_dalyCost.C_date = c_date;
            tbl_dalyCost.cost = cost;
            return tbl_dalyCost;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String C_date
        {
            get
            {
                return _C_date;
            }
            set
            {
                if (_C_date != value)
                {
                    OnC_dateChanging(value);
                    ReportPropertyChanging("C_date");
                    _C_date = StructuralObject.SetValidValue(value, false, "C_date");
                    ReportPropertyChanged("C_date");
                    OnC_dateChanged();
                }
            }
        }
        private global::System.String _C_date;
        partial void OnC_dateChanging(global::System.String value);
        partial void OnC_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cost
        {
            get
            {
                return _cost;
            }
            set
            {
                OncostChanging(value);
                ReportPropertyChanging("cost");
                _cost = StructuralObject.SetValidValue(value, "cost");
                ReportPropertyChanged("cost");
                OncostChanged();
            }
        }
        private global::System.Int32 _cost;
        partial void OncostChanging(global::System.Int32 value);
        partial void OncostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> meal
        {
            get
            {
                return _meal;
            }
            set
            {
                OnmealChanging(value);
                ReportPropertyChanging("meal");
                _meal = StructuralObject.SetValidValue(value, "meal");
                ReportPropertyChanged("meal");
                OnmealChanged();
            }
        }
        private Nullable<global::System.Int32> _meal;
        partial void OnmealChanging(Nullable<global::System.Int32> value);
        partial void OnmealChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DinningManagementModel", Name="tbl_MealInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_MealInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_MealInfo object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="e_id">Initial value of the E_id property.</param>
        /// <param name="m_date">Initial value of the m_date property.</param>
        public static tbl_MealInfo Createtbl_MealInfo(global::System.Int32 id, global::System.Int32 e_id, global::System.String m_date)
        {
            tbl_MealInfo tbl_MealInfo = new tbl_MealInfo();
            tbl_MealInfo.id = id;
            tbl_MealInfo.E_id = e_id;
            tbl_MealInfo.m_date = m_date;
            return tbl_MealInfo;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 E_id
        {
            get
            {
                return _E_id;
            }
            set
            {
                OnE_idChanging(value);
                ReportPropertyChanging("E_id");
                _E_id = StructuralObject.SetValidValue(value, "E_id");
                ReportPropertyChanged("E_id");
                OnE_idChanged();
            }
        }
        private global::System.Int32 _E_id;
        partial void OnE_idChanging(global::System.Int32 value);
        partial void OnE_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String m_date
        {
            get
            {
                return _m_date;
            }
            set
            {
                Onm_dateChanging(value);
                ReportPropertyChanging("m_date");
                _m_date = StructuralObject.SetValidValue(value, false, "m_date");
                ReportPropertyChanged("m_date");
                Onm_dateChanged();
            }
        }
        private global::System.String _m_date;
        partial void Onm_dateChanging(global::System.String value);
        partial void Onm_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> meal
        {
            get
            {
                return _meal;
            }
            set
            {
                OnmealChanging(value);
                ReportPropertyChanging("meal");
                _meal = StructuralObject.SetValidValue(value, "meal");
                ReportPropertyChanged("meal");
                OnmealChanged();
            }
        }
        private Nullable<global::System.Int32> _meal;
        partial void OnmealChanging(Nullable<global::System.Int32> value);
        partial void OnmealChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DinningManagementModel", "FK_tbl_MealInfo_tbl_userInfo", "tbl_userInfo")]
        public tbl_userInfo tbl_userInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_userInfo>("DinningManagementModel.FK_tbl_MealInfo_tbl_userInfo", "tbl_userInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_userInfo>("DinningManagementModel.FK_tbl_MealInfo_tbl_userInfo", "tbl_userInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_userInfo> tbl_userInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_userInfo>("DinningManagementModel.FK_tbl_MealInfo_tbl_userInfo", "tbl_userInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_userInfo>("DinningManagementModel.FK_tbl_MealInfo_tbl_userInfo", "tbl_userInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DinningManagementModel", Name="tbl_Uaccount")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Uaccount : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Uaccount object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="e_id">Initial value of the E_id property.</param>
        public static tbl_Uaccount Createtbl_Uaccount(global::System.Int32 id, global::System.Int32 e_id)
        {
            tbl_Uaccount tbl_Uaccount = new tbl_Uaccount();
            tbl_Uaccount.id = id;
            tbl_Uaccount.E_id = e_id;
            return tbl_Uaccount;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 E_id
        {
            get
            {
                return _E_id;
            }
            set
            {
                OnE_idChanging(value);
                ReportPropertyChanging("E_id");
                _E_id = StructuralObject.SetValidValue(value, "E_id");
                ReportPropertyChanged("E_id");
                OnE_idChanged();
            }
        }
        private global::System.Int32 _E_id;
        partial void OnE_idChanging(global::System.Int32 value);
        partial void OnE_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> account
        {
            get
            {
                return _account;
            }
            set
            {
                OnaccountChanging(value);
                ReportPropertyChanging("account");
                _account = StructuralObject.SetValidValue(value, "account");
                ReportPropertyChanged("account");
                OnaccountChanged();
            }
        }
        private Nullable<global::System.Int32> _account;
        partial void OnaccountChanging(Nullable<global::System.Int32> value);
        partial void OnaccountChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DinningManagementModel", "FK_tbl_Uaccount_tbl_userInfo", "tbl_userInfo")]
        public tbl_userInfo tbl_userInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_userInfo>("DinningManagementModel.FK_tbl_Uaccount_tbl_userInfo", "tbl_userInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_userInfo>("DinningManagementModel.FK_tbl_Uaccount_tbl_userInfo", "tbl_userInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_userInfo> tbl_userInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_userInfo>("DinningManagementModel.FK_tbl_Uaccount_tbl_userInfo", "tbl_userInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_userInfo>("DinningManagementModel.FK_tbl_Uaccount_tbl_userInfo", "tbl_userInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DinningManagementModel", Name="tbl_userInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_userInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_userInfo object.
        /// </summary>
        /// <param name="e_id">Initial value of the E_id property.</param>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="password">Initial value of the password property.</param>
        public static tbl_userInfo Createtbl_userInfo(global::System.Int32 e_id, global::System.String username, global::System.String password)
        {
            tbl_userInfo tbl_userInfo = new tbl_userInfo();
            tbl_userInfo.E_id = e_id;
            tbl_userInfo.username = username;
            tbl_userInfo.password = password;
            return tbl_userInfo;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 E_id
        {
            get
            {
                return _E_id;
            }
            set
            {
                if (_E_id != value)
                {
                    OnE_idChanging(value);
                    ReportPropertyChanging("E_id");
                    _E_id = StructuralObject.SetValidValue(value, "E_id");
                    ReportPropertyChanged("E_id");
                    OnE_idChanged();
                }
            }
        }
        private global::System.Int32 _E_id;
        partial void OnE_idChanging(global::System.Int32 value);
        partial void OnE_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fname
        {
            get
            {
                return _fname;
            }
            set
            {
                OnfnameChanging(value);
                ReportPropertyChanging("fname");
                _fname = StructuralObject.SetValidValue(value, true, "fname");
                ReportPropertyChanged("fname");
                OnfnameChanged();
            }
        }
        private global::System.String _fname;
        partial void OnfnameChanging(global::System.String value);
        partial void OnfnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lname
        {
            get
            {
                return _lname;
            }
            set
            {
                OnlnameChanging(value);
                ReportPropertyChanging("lname");
                _lname = StructuralObject.SetValidValue(value, true, "lname");
                ReportPropertyChanged("lname");
                OnlnameChanged();
            }
        }
        private global::System.String _lname;
        partial void OnlnameChanging(global::System.String value);
        partial void OnlnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String designation
        {
            get
            {
                return _designation;
            }
            set
            {
                OndesignationChanging(value);
                ReportPropertyChanging("designation");
                _designation = StructuralObject.SetValidValue(value, true, "designation");
                ReportPropertyChanged("designation");
                OndesignationChanged();
            }
        }
        private global::System.String _designation;
        partial void OndesignationChanging(global::System.String value);
        partial void OndesignationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false, "username");
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false, "password");
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DinningManagementModel", "FK_tbl_MealInfo_tbl_userInfo", "tbl_MealInfo")]
        public EntityCollection<tbl_MealInfo> tbl_MealInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_MealInfo>("DinningManagementModel.FK_tbl_MealInfo_tbl_userInfo", "tbl_MealInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_MealInfo>("DinningManagementModel.FK_tbl_MealInfo_tbl_userInfo", "tbl_MealInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DinningManagementModel", "FK_tbl_Uaccount_tbl_userInfo", "tbl_Uaccount")]
        public EntityCollection<tbl_Uaccount> tbl_Uaccount
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_Uaccount>("DinningManagementModel.FK_tbl_Uaccount_tbl_userInfo", "tbl_Uaccount");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_Uaccount>("DinningManagementModel.FK_tbl_Uaccount_tbl_userInfo", "tbl_Uaccount", value);
                }
            }
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="DinningManagementModel", Name="SP_NumberStopMeal_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SP_NumberStopMeal_Result : ComplexObject
    {
        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Column1
        {
            get
            {
                return _Column1;
            }
            set
            {
                OnColumn1Changing(value);
                ReportPropertyChanging("Column1");
                _Column1 = StructuralObject.SetValidValue(value, "Column1");
                ReportPropertyChanged("Column1");
                OnColumn1Changed();
            }
        }
        private Nullable<global::System.Int32> _Column1;
        partial void OnColumn1Changing(Nullable<global::System.Int32> value);
        partial void OnColumn1Changed();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="DinningManagementModel", Name="sp_returnData_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class sp_returnData_Result : ComplexObject
    {
        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Member
        {
            get
            {
                return _Member;
            }
            set
            {
                OnMemberChanging(value);
                ReportPropertyChanging("Member");
                _Member = StructuralObject.SetValidValue(value, "Member");
                ReportPropertyChanged("Member");
                OnMemberChanged();
            }
        }
        private Nullable<global::System.Int32> _Member;
        partial void OnMemberChanging(Nullable<global::System.Int32> value);
        partial void OnMemberChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="DinningManagementModel", Name="SP_stopNum_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SP_stopNum_Result : ComplexObject
    {
        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Member
        {
            get
            {
                return _Member;
            }
            set
            {
                OnMemberChanging(value);
                ReportPropertyChanging("Member");
                _Member = StructuralObject.SetValidValue(value, "Member");
                ReportPropertyChanged("Member");
                OnMemberChanged();
            }
        }
        private Nullable<global::System.Int32> _Member;
        partial void OnMemberChanging(Nullable<global::System.Int32> value);
        partial void OnMemberChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="DinningManagementModel", Name="SP_stopNum_Result1")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SP_stopNum_Result1 : ComplexObject
    {
        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Member
        {
            get
            {
                return _Member;
            }
            set
            {
                OnMemberChanging(value);
                ReportPropertyChanging("Member");
                _Member = StructuralObject.SetValidValue(value, "Member");
                ReportPropertyChanged("Member");
                OnMemberChanged();
            }
        }
        private Nullable<global::System.Int32> _Member;
        partial void OnMemberChanging(Nullable<global::System.Int32> value);
        partial void OnMemberChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="DinningManagementModel", Name="SP_stopNum_Result2")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SP_stopNum_Result2 : ComplexObject
    {
        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Member
        {
            get
            {
                return _Member;
            }
            set
            {
                OnMemberChanging(value);
                ReportPropertyChanging("Member");
                _Member = StructuralObject.SetValidValue(value, "Member");
                ReportPropertyChanged("Member");
                OnMemberChanged();
            }
        }
        private Nullable<global::System.Int32> _Member;
        partial void OnMemberChanging(Nullable<global::System.Int32> value);
        partial void OnMemberChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="DinningManagementModel", Name="SP_StopUser_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SP_StopUser_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SP_StopUser_Result object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="e_id">Initial value of the E_id property.</param>
        /// <param name="m_date">Initial value of the m_date property.</param>
        public static SP_StopUser_Result CreateSP_StopUser_Result(global::System.Int32 id, global::System.Int32 e_id, global::System.DateTime m_date)
        {
            SP_StopUser_Result sP_StopUser_Result = new SP_StopUser_Result();
            sP_StopUser_Result.id = id;
            sP_StopUser_Result.E_id = e_id;
            sP_StopUser_Result.m_date = m_date;
            return sP_StopUser_Result;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value, "id");
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 E_id
        {
            get
            {
                return _E_id;
            }
            set
            {
                OnE_idChanging(value);
                ReportPropertyChanging("E_id");
                _E_id = StructuralObject.SetValidValue(value, "E_id");
                ReportPropertyChanged("E_id");
                OnE_idChanged();
            }
        }
        private global::System.Int32 _E_id;
        partial void OnE_idChanging(global::System.Int32 value);
        partial void OnE_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime m_date
        {
            get
            {
                return _m_date;
            }
            set
            {
                Onm_dateChanging(value);
                ReportPropertyChanging("m_date");
                _m_date = StructuralObject.SetValidValue(value, "m_date");
                ReportPropertyChanged("m_date");
                Onm_dateChanged();
            }
        }
        private global::System.DateTime _m_date;
        partial void Onm_dateChanging(global::System.DateTime value);
        partial void Onm_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> meal
        {
            get
            {
                return _meal;
            }
            set
            {
                OnmealChanging(value);
                ReportPropertyChanging("meal");
                _meal = StructuralObject.SetValidValue(value, "meal");
                ReportPropertyChanged("meal");
                OnmealChanged();
            }
        }
        private Nullable<global::System.Int32> _meal;
        partial void OnmealChanging(Nullable<global::System.Int32> value);
        partial void OnmealChanged();

        #endregion

    }

    #endregion

}
